spring:
  application:
    name: holiday-camp-backend

  datasource:
    url: jdbc:postgres://${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_PARAMS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.springframework.jdbc.core: TRACE

server:
  error:
    whitelabel:
      enabled: false
    path: /error
